# after-startup-command = ['exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
# exec-on-workspace-change = ['/bin/bash', '-c',
#   'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
#   'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
# ]

# Start AeroSpace at login
start-at-login = false

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 5
inner.vertical =   0
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

# [[on-window-detected]]
# if.app-id = 'com.apple.systempreferences'
# if.app-name-regex-substring = 'settings'
# if.window-title-regex-substring = 'substring'
# if.workspace = 'workspace-name'
# if.during-aerospace-startup = true
# check-further-callbacks = true
# run = ['layout floating', 'move-node-to-workspace S']  # The callback itself

# [[on-window-detected]]
# if.app-name-regex-substring = 'telegram'
# run = 'layout floating'

# [[on-window-detected]]
# if.app-name-regex-substring = 'finder'
# run = 'layout floating'

# [[on-window-detected]]
# if.app-name-regex-substring = 'safari'
# run = 'layout floating'
 
# [[on-window-detected]]
# if.app-name-regex-substring = 'camera'
# run = 'layout floating'

# [[on-window-detected]]
# if.app-name-regex-substring = 'quicktime'
# run = 'layout floating'


[mode.main.binding]

# Modes
alt-shift-semicolon = 'mode service'
alt-shift-enter = 'mode apps'
alt-shift-l = 'mode layouts'
alt-shift-r = 'mode resize'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-shift-period = 'focus right'
alt-shift-comma = 'focus left'


# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout

down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main']

[mode.apps.binding]
esc = 'mode main'
left = 'focus left'
down = 'focus down'
up = 'focus up'
right = 'focus right'

w = 'exec-and-forget open -a /Applications/Warp.app'

[mode.layouts.binding]
esc = 'mode main'
f = 'layout floating tiling'
shift-f = "fullscreen"
comma = 'layout accordion horizontal'
period = 'layout tiles horizontal'

[mode.resize.binding]
esc = 'mode main'
minus = 'resize smart -50'
equal = 'resize smart +50'